/**
 * The runtime gate, run before anything else in the process.
 *
 * Frodon is compiled for Bun, not Node: it reads files through `Bun.file`,
 * matches globs with `Bun.Glob`, shells out with `Bun.spawn`, and gives every
 * terminal window a real PTY through `Bun.Terminal`. On the wrong runtime — or
 * a Bun too old for one of those — the failure surfaces far from its cause: a
 * `TypeError` inside a React effect, hours into a session, with the TUI already
 * holding the terminal. This turns that into a sentence on a normal terminal,
 * before the alternate screen is ever entered.
 *
 * `dist/frodon` (the published `bin`, generated by scripts/build.ts) makes the
 * same checks in POSIX sh and catches the one case this file can't: Bun missing
 * entirely, where nothing here ever runs.
 */
import {
  RuntimeProblem,
  type RuntimeCheck,
  type Version,
} from './preflight.def';
import { BUN_INSTALL_URL, MINIMUM_BUN } from './preflight.constant';

/**
 * Reduces a version string to its three numbers, ignoring any pre-release or
 * build suffix (`1.3.0-canary.20250101` → `[1, 3, 0]`). Returns null for
 * anything that doesn't start with a number, which callers treat as "can't
 * tell" rather than "too old".
 */
export function parseVersion(version: string): Version | null {
  const [base] = version.trim().split(/[-+]/, 1);
  const parts = (base ?? '').split('.');
  if (parts.length === 0) return null;

  const numbers = parts.slice(0, 3).map((part) => Number.parseInt(part, 10));
  if (numbers.length === 0 || Number.isNaN(numbers[0])) return null;

  return [numbers[0]!, numbers[1] || 0, numbers[2] || 0];
}

/** True when `version` is at least `minimum`, comparing field by field. */
export function satisfies(version: Version, minimum: Version): boolean {
  for (let i = 0; i < 3; i++) {
    if (version[i]! > minimum[i]!) return true;
    if (version[i]! < minimum[i]!) return false;
  }
  return true;
}

/**
 * Inspects the runtime this process is running on.
 *
 * An unparseable `Bun.version` passes: a runtime that calls itself Bun and
 * reports a version we don't recognise is likelier to be newer than ours than
 * broken, and refusing to start over a string we failed to read would be the
 * worse error of the two.
 */
export function checkRuntime(): RuntimeCheck {
  if (typeof Bun === 'undefined') {
    return { ok: false, problem: RuntimeProblem.NOT_BUN };
  }

  const found = parseVersion(Bun.version);
  const minimum = parseVersion(MINIMUM_BUN)!;
  if (!found) return { ok: true };

  if (!satisfies(found, minimum)) {
    return {
      ok: false,
      problem: RuntimeProblem.BUN_TOO_OLD,
      found: Bun.version,
    };
  }

  return { ok: true };
}

/** The message shown on a failed check, written for someone who hit it blind. */
export function describeProblem(check: Extract<RuntimeCheck, { ok: false }>): string {
  switch (check.problem) {
    case RuntimeProblem.NOT_BUN:
      return (
        `Frodon runs on Bun ${MINIMUM_BUN} or newer, and this isn't Bun.\n\n` +
        `It's built against Bun's own APIs — its embedded terminals are Bun\n` +
        `PTYs — so Node can't run it, even though npm can install it.\n\n` +
        `  Install Bun:  curl -fsSL ${BUN_INSTALL_URL}/install | bash\n` +
        `  Then run:     frodon\n`
      );
    case RuntimeProblem.BUN_TOO_OLD:
      return (
        `Frodon needs Bun ${MINIMUM_BUN} or newer — this is Bun ${check.found}.\n\n` +
        `Bun ${MINIMUM_BUN} is where the PTY API behind Frodon's terminals\n` +
        `landed; on anything older the terminal windows can't open.\n\n` +
        `  Upgrade:  bun upgrade\n`
      );
  }
}

/**
 * Runs the check and, on failure, prints why and exits non-zero.
 *
 * Must be called before any module that touches a Bun API is evaluated —
 * `src/index.tsx` keeps the rest of the app behind a dynamic import for exactly
 * this reason. Writes to stderr directly: there's no renderer yet, and
 * `console` is the thing we spend the rest of the app avoiding.
 */
export function assertSupportedRuntime(): void {
  const check = checkRuntime();
  if (check.ok) return;

  process.stderr.write(`\n${describeProblem(check)}\n`);
  process.exit(1);
}
