/**
 * Generates `src/lib/language/language.constant.ts` — a map from file
 * extension to the refractor language id used to highlight it.
 *
 * It combines two sources of truth:
 *  - The GitHub "Programming_Languages_Extensions" gist, which maps human
 *    language names to their file extensions (great extension coverage, but
 *    the names don't match refractor's ids).
 *  - The refractor `lang/` directory, whose filenames ARE the language ids and
 *    whose modules declare their aliases.
 *
 * Run with: `bun scripts/generate-language-map.ts`
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const GIST_URL =
  'https://gist.githubusercontent.com/ppisarczyk/43962d06686722d26d176fad46879d41/raw';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const langDir = join(root, 'node_modules/refractor/lang');
const outFile = join(root, 'src/lib/language/language.constant.ts');

interface GistLanguage {
  name: string;
  type: string;
  extensions?: string[];
}

/** Refractor names that a normalized gist name can't reach on its own. */
const NAME_OVERRIDES: Record<string, string> = {
  'C++': 'cpp',
  'C#': 'csharp',
  'F#': 'fsharp',
  'Objective-C': 'objectivec',
  'Objective-C++': 'cpp',
  Shell: 'bash',
  'Vim script': 'vim',
  'GCC Machine Description': 'c',
  'Emacs Lisp': 'lisp',
  'Common Lisp': 'lisp',
  'Standard ML': 'sml',
  'F*': 'fsharp',
  'Visual Basic': 'visual-basic',
  Gettext: 'gettext',
  'Jupyter Notebook': 'json',
  reStructuredText: 'rest',
  'Unix Assembly': 'asm6502',
  Assembly: 'asm6502',
};

/** Hot extensions that map to several languages; pin the sensible default. */
const EXTENSION_OVERRIDES: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  h: 'c',
  m: 'objectivec',
  pl: 'perl',
  r: 'r',
  v: 'verilog',
  sql: 'sql',
  md: 'markdown',
};

function normalize(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
}

function readRefractorLanguages(): {
  ids: Set<string>;
  aliasToId: Map<string, string>;
} {
  const ids = new Set<string>();
  const aliasToId = new Map<string, string>();

  for (const file of readdirSync(langDir)) {
    if (!file.endsWith('.js')) continue;
    const id = file.slice(0, -3);
    ids.add(id);

    const source = readFileSync(join(langDir, file), 'utf-8');
    const match = source.match(/\.aliases\s*=\s*\[([^\]]*)\]/);
    if (!match) continue;
    for (const raw of match[1]!.split(',')) {
      const alias = raw.trim().replace(/^['"]|['"]$/g, '');
      if (alias) aliasToId.set(normalize(alias), id);
    }
  }

  return { ids, aliasToId };
}

function resolveId(
  name: string,
  ids: Set<string>,
  aliasToId: Map<string, string>
): string | null {
  if (NAME_OVERRIDES[name]) return NAME_OVERRIDES[name]!;
  const key = normalize(name);
  if (ids.has(key)) return key;
  if (aliasToId.has(key)) return aliasToId.get(key)!;
  return null;
}

async function main() {
  const { ids, aliasToId } = readRefractorLanguages();

  const gist: GistLanguage[] = await fetch(GIST_URL).then((r) => r.json());
  gist.sort((a, b) => a.name.localeCompare(b.name));

  const extToId = new Map<string, string>();
  let resolved = 0;

  for (const lang of gist) {
    const id = resolveId(lang.name, ids, aliasToId);
    if (!id || !lang.extensions) continue;
    resolved++;
    for (const ext of lang.extensions) {
      const key = ext.replace(/^\./, '').toLowerCase();
      if (!key) continue;
      // First language (alphabetical) wins a contested extension.
      if (!extToId.has(key)) extToId.set(key, id);
    }
  }

  // Apply deliberate overrides last so they always win.
  for (const [ext, id] of Object.entries(EXTENSION_OVERRIDES)) {
    if (ids.has(id)) extToId.set(ext, id);
  }

  const entries = [...extToId.entries()].sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(([ext, id]) => `  ${JSON.stringify(ext)}: ${JSON.stringify(id)},`)
    .join('\n');

  const output = `// AUTO-GENERATED by scripts/generate-language-map.ts — do not edit by hand.
// Maps a lowercase file extension (no leading dot) to a refractor language id.
// Source: github.com/ppisarczyk/43962d06686722d26d176fad46879d41 + refractor.

export const EXTENSION_LANGUAGE: Record<string, string> = {
${body}
};
`;

  writeFileSync(outFile, output);
  console.log(
    `Resolved ${resolved}/${gist.length} languages, ${entries.length} extensions -> ${outFile}`
  );
}

main();
